/// App strings in English and Tamil. Tamil is the default language.
class AppStrings {
  AppStrings._();

  static const Map<String, String> _en = {
    'appName': 'BusTracker',
    'tagline': 'Live bus tracking, village to village',
    'passengerMode': 'I am a passenger',
    'driverMode': 'I am a bus driver',
    'continue': 'Continue',
    'cancel': 'Cancel',
    'retry': 'Retry',
    'back': 'Back',
    'save': 'Save',
    'search': 'Search',
    'loading': 'Loading…',
    'error': 'Something went wrong',
    'noResults': 'No results found',
    'empty': 'Nothing here yet',
    'online': 'Online',
    'offline': 'Offline',
    'refresh': 'Refresh',

    // District / village selection
    'selectDistrict': 'Select your district',
    'autoDetect': 'Detect automatically',
    'detecting': 'Detecting district…',
    'detectFailed': 'Could not detect your location.',
    'allowLocation':
        'Allow location access to automatically find your district.',
    'enableLocation': 'Enable location',
    'searchVillages': 'Search villages…',
    'fromVillage': 'From village',
    'toVillage': 'To village',
    'chooseFrom': 'Choose starting village',
    'chooseTo': 'Choose destination village',
    'findBuses': 'Find buses',
    'swap': 'Swap',
    'pickDistrict': 'Pick a district first',

    // Results
    'busesFound': 'buses found',
    'noBusesNow': 'No buses running on this route right now',
    'routeActive': 'active route',
    'notVerified': 'not verified yet',
    'viewMap': 'View on map',
    'reached': 'Reached',
    'departed': 'Departed',
    'atStop': 'At stop',

    // Bus detail / map
    'live': 'LIVE',
    'liveNow': 'Live now',
    'stale': 'Last update long ago',
    'offlineBus': 'Bus offline',
    'eta': 'ETA',
    'etaMinutes': 'ETA {m} min',
    'distanceKm': '{km} km away',
    'distanceM': '{m} m away',
    'speed': '{s} km/h',
    'stops': 'Stops',
    'tripEnded': 'This trip has ended',
    'noSignal': 'Waiting for signal…',
    'follow': 'Follow',
    'alertMe': 'Alert me at this stop',
    'alertSubscribed': 'Alert set. We will notify you.',
    'alertUnavailable': 'Notifications are not available.',
    'addFavorite': 'Save this route',
    'favoriteAdded': 'Route saved to favorites',
    'history': 'Recent track',
    'minutesAgo': '{m} min ago',
    'justNow': 'Just now',

    // Favorites
    'favorites': 'Favorites',
    'noFavorites': 'No saved routes. Save a route to find it fast next time.',
    'removeFavorite': 'Remove',

    // Driver
    'driverLogin': 'Driver login',
    'driverPhoneHint': 'Enter mobile number',
    'sendOtp': 'Send OTP',
    'otpSent': 'OTP sent to {phone}',
    'enterOtp': 'Enter the 6-digit OTP',
    'verify': 'Verify',
    'resendOtp': 'Resend OTP',
    'wrongOtp': 'Incorrect OTP. Please try again.',
    'otpRateLimited': 'Too many attempts. Please wait.',
    'myBuses': 'My buses',
    'addBus': 'Add bus',
    'busNumber': 'Bus number (e.g. 21A)',
    'busName': 'Bus name (optional)',
    'rtoNumber': 'RTO number (e.g. TN-32-1234)',
    'busType': 'Bus type',
    'govt': 'Government',
    'private': 'Private',
    'register': 'Register',
    'busRegistered': 'Bus registered for verification.',
    'verification': 'Verification',
    'pending': 'Pending',
    'approved': 'Approved',
    'rejected': 'Rejected',
    'pickRouteDistrict': 'Select route district',
    'chooseRouteFrom': 'Route start village',
    'chooseRouteTo': 'Route end village',
    'buildRoute': 'Build route',
    'routeBuilding': 'Building route…',
    'routeReady': 'Route ready',
    'routeFailed': 'Could not build a route for these villages.',
    'assignToBus': 'Use for trip',
    'assignBus': 'Choose a bus',
    'routeAssigned': 'Route assigned',
    'startSharing': 'Start sharing',
    'stopSharing': 'Stop sharing',
    'sharing': 'Sharing location',
    'pointsSent': 'updates sent',
    'tripActive': 'Trip active',
    'noRouteAssigned': 'Assign a route to this bus first.',
    'noBusesYet': 'Register a bus to start sharing.',
    'tapStart': 'Tap Start sharing to begin',
    'backgroundNotice':
        'Location sharing continues even when the app is in the background.',
    'endTrip': 'End trip',
    'endTripConfirm': 'End this trip? Passengers will stop seeing the bus.',
    'logout': 'Log out',
    'loggedOut': 'Logged out',

    // Misc
    'permissionDenied': 'Location permission is required to continue.',
    'permissionDeniedForever': 'Location permission was denied permanently. '
        'Please enable it in Settings.',
  };

  static const Map<String, String> _ta = {
    'appName': 'பஸ் ட்ராக்கர்',
    'tagline': 'நேரடி பேருந்து கண்காணிப்பு, ஊர் வாரியாக',
    'passengerMode': 'நான் பயணி',
    'driverMode': 'நான் பேருந்து ஓட்டுநர்',
    'continue': 'தொடரவும்',
    'cancel': 'ரத்து',
    'retry': 'மீண்டும் முயற்சி',
    'back': 'பின்',
    'save': 'சேமி',
    'search': 'தேடு',
    'loading': 'ஏற்றுகிறது…',
    'error': 'ஏதோ பிழை ஏற்பட்டது',
    'noResults': 'முடிவுகள் இல்லை',
    'empty': 'இங்கு எதுவும் இல்லை',
    'online': 'ஆன்லைன்',
    'offline': 'ஆஃப்லைன்',
    'refresh': 'புதுப்பி',

    'selectDistrict': 'உங்கள் மாவட்டத்தை தேர்ந்தெடுக்கவும்',
    'autoDetect': 'தானாக கண்டறியவும்',
    'detecting': 'மாவட்டம் கண்டறிகிறது…',
    'detectFailed': 'உங்கள் இடத்தை கண்டறிய முடியவில்லை.',
    'allowLocation':
        'உங்கள் மாவட்டத்தை தானாக கண்டறிய இருப்பிட அனுமதி தேவை.',
    'enableLocation': 'இருப்பிடத்தை இயக்கவும்',
    'searchVillages': 'ஊர்களை தேடுங்கள்…',
    'fromVillage': 'புறப்படும் ஊர்',
    'toVillage': 'சேருமிட ஊர்',
    'chooseFrom': 'புறப்படும் ஊரை தேர்வு செய்யவும்',
    'chooseTo': 'சேருமிட ஊரை தேர்வு செய்யவும்',
    'findBuses': 'பேருந்துகளை கண்டறியவும்',
    'swap': 'மாற்று',
    'pickDistrict': 'முதலில் ஒரு மாவட்டத்தை தேர்வு செய்யவும்',

    'busesFound': 'பேருந்துகள் கண்டறியப்பட்டன',
    'noBusesNow': 'இந்த வழித்தடத்தில் இப்போது பேருந்துகள் இல்லை',
    'routeActive': 'செயலில் உள்ள வழித்தடம்',
    'notVerified': 'இன்னும் சரிபார்க்கப்படவில்லை',
    'viewMap': 'வரைபடத்தில் பார்க்கவும்',
    'reached': 'சென்று சேர்ந்தது',
    'departed': 'புறப்பட்டது',
    'atStop': 'நிறுத்தத்தில்',

    'live': 'நேரடி',
    'liveNow': 'இப்போது நேரடி',
    'stale': 'நீண்ட நேரமாக புதுப்பிப்பு இல்லை',
    'offlineBus': 'பேருந்து ஆஃப்லைன்',
    'eta': 'சேரும் நேரம்',
    'etaMinutes': 'சேர நேரம் {m} நிமிடம்',
    'distanceKm': '{km} கி.மீ தொலைவில்',
    'distanceM': '{m} மீட்டர் தொலைவில்',
    'speed': '{s} கி.மீ/மணி',
    'stops': 'நிறுத்தங்கள்',
    'tripEnded': 'இந்த பயணம் முடிந்துவிட்டது',
    'noSignal': 'சிக்னல் காத்திருக்கிறது…',
    'follow': 'பின்தொடர்',
    'alertMe': 'இந்த நிறுத்தத்தில் எனக்கு அறிவிப்பு',
    'alertSubscribed': 'அறிவிப்பு அமைக்கப்பட்டது. உங்களுக்கு தெரிவிப்போம்.',
    'alertUnavailable': 'அறிவிப்புகள் கிடைக்கவில்லை.',
    'addFavorite': 'இந்த வழித்தடத்தை சேமிக்கவும்',
    'favoriteAdded': 'வழித்தடம் சேமிக்கப்பட்டது',
    'history': 'சமீபத்திய பாதை',
    'minutesAgo': '{m} நிமிடங்களுக்கு முன்',
    'justNow': 'இப்போதுதான்',

    'favorites': 'சேமித்தவை',
    'noFavorites': 'சேமித்த வழித்தடங்கள் இல்லை. அடுத்த முறை விரைவாக கண்டறிய ஒரு வழித்தடத்தை சேமிக்கவும்.',
    'removeFavorite': 'நீக்கு',

    'driverLogin': 'ஓட்டுநர் உள்நுழைவு',
    'driverPhoneHint': 'மொபைல் எண்ணை உள்ளிடவும்',
    'sendOtp': 'OTP அனுப்பு',
    'otpSent': 'OTP {phone} க்கு அனுப்பப்பட்டது',
    'enterOtp': '6 இலக்க OTP ஐ உள்ளிடவும்',
    'verify': 'சரிபார்',
    'resendOtp': 'மீண்டும் OTP அனுப்பு',
    'wrongOtp': 'தவறான OTP. மீண்டும் முயற்சிக்கவும்.',
    'otpRateLimited': 'அதிக முயற்சிகள். சிறிது நேரம் கழித்து முயற்சிக்கவும்.',
    'myBuses': 'என் பேருந்துகள்',
    'addBus': 'பேருந்து சேர்',
    'busNumber': 'பேருந்து எண் (எ.கா. 21A)',
    'busName': 'பேருந்து பெயர் (விருப்பம்)',
    'rtoNumber': 'RTO எண் (எ.கா. TN-32-1234)',
    'busType': 'பேருந்து வகை',
    'govt': 'அரசு',
    'private': 'தனியார்',
    'register': 'பதிவு',
    'busRegistered': 'பேருந்து சரிபார்ப்புக்கு பதிவு செய்யப்பட்டது.',
    'verification': 'சரிபார்ப்பு',
    'pending': 'நிலுவையில்',
    'approved': 'அங்கீகரிக்கப்பட்டது',
    'rejected': 'நிராகரிக்கப்பட்டது',
    'pickRouteDistrict': 'வழித்தட மாவட்டத்தை தேர்வு செய்யவும்',
    'chooseRouteFrom': 'வழித்தட தொடக்க ஊர்',
    'chooseRouteTo': 'வழித்தட இறுதி ஊர்',
    'buildRoute': 'வழித்தடம் உருவாக்கு',
    'routeBuilding': 'வழித்தடம் உருவாகிறது…',
    'routeReady': 'வழித்தடம் தயார்',
    'routeFailed': 'இந்த ஊர்களுக்கு வழித்தடம் உருவாக்க முடியவில்லை.',
    'assignToBus': 'பயணத்திற்கு பயன்படுத்து',
    'assignBus': 'பேருந்தை தேர்வு செய்யவும்',
    'routeAssigned': 'வழித்தடம் ஒதுக்கப்பட்டது',
    'startSharing': 'பகிர ஆரம்பி',
    'stopSharing': 'பகிர்வதை நிறுத்து',
    'sharing': 'இருப்பிடம் பகிரப்படுகிறது',
    'pointsSent': 'புதுப்பிப்புகள் அனுப்பப்பட்டன',
    'tripActive': 'பயணம் செயலில் உள்ளது',
    'noRouteAssigned': 'முதலில் இந்த பேருந்துக்கு ஒரு வழித்தடத்தை ஒதுக்கவும்.',
    'noBusesYet': 'பகிர ஆரம்பிக்க பேருந்தை பதிவு செய்யவும்.',
    'tapStart': 'தொடங்க "பகிர ஆரம்பி" ஐ அழுத்தவும்',
    'backgroundNotice':
        'பயன்பாடு பின்னணியில் இருந்தாலும் இருப்பிடம் பகிரப்படும்.',
    'endTrip': 'பயணத்தை முடி',
    'endTripConfirm': 'இந்த பயணத்தை முடிக்கவா? பயணிகள் பேருந்தை பார்க்க முடியாது.',
    'logout': 'வெளியேறு',
    'loggedOut': 'வெளியேறியது',

    'permissionDenied': 'தொடர இருப்பிட அனுமதி தேவை.',
    'permissionDeniedForever':
        'இருப்பிட அனுமதி நிரந்தரமாக மறுக்கப்பட்டது. அமைப்புகளில் இயக்கவும்.',
  };

  static Map<String, String> stringsFor(String language) =>
      language == 'ta' ? _ta : _en;

  static String resolve(String language, String key, {Map<String, String>? args}) {
    final table = stringsFor(language);
    var text = table[key] ?? _en[key] ?? key;
    if (args != null) {
      for (final e in args.entries) {
        text = text.replaceAll('{$e.key}', e.value);
      }
    }
    return text;
  }
}
